"""empty message

Revision ID: 16985731cb0f
Revises: 
Create Date: 2022-12-19 10:04:36.109738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16985731cb0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('continent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_population', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('continent', schema=None) as batch_op:
        batch_op.drop_column('total_population')

    # ### end Alembic commands ###
